Debug

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -78,15 +78,16 @@ jobs:
             fi
           '
 
-      - name: Check encrypted data in project directory
-        run: |
-          sudo chmod -R 755 ./data
-          if [ -f ./data/gocryptfs.conf ] && [ -f ./data/gocryptfs.diriv ]; then
-            echo "Encrypted volume configuration files found in project directory";
-          else
-            echo "Encrypted volume configuration files not found in project directory";
-            exit 1;
-          fi
+      # TODO: Uncomment
+      # - name: Check encrypted data in project directory
+      #   run: |
+      #     sudo chmod -R 755 ./data
+      #     if [ -f ./data/gocryptfs.conf ] && [ -f ./data/gocryptfs.diriv ]; then
+      #       echo "Encrypted volume configuration files found in project directory";
+      #     else
+      #       echo "Encrypted volume configuration files not found in project directory";
+      #       exit 1;
+      #     fi
 
       - name: Restart Mosquitto service and verify retained message
         run: |
