Add additional check for encryption files on host

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -49,7 +49,7 @@ jobs:
           docker-compose logs mosquitto
           docker-compose down
 
-      - name: Check encrypted data
+      - name: Check encrypted data in container
         run: |
           docker run --rm -v $(pwd)/data:/encrypted alpine:latest /bin/sh -c '
             if [ -f /encrypted/gocryptfs.conf ] && [ -f /encrypted/gocryptfs.diriv ]; then
@@ -59,3 +59,12 @@ jobs:
               exit 1;
             fi
           '
+
+      - name: Check encrypted data in project directory
+        run: |
+          if [ -f ./data/gocryptfs.conf ] && [ -f ./data/gocryptfs.diriv ]; then
+            echo "Encrypted volume configuration files found in project directory";
+          else
+            echo "Encrypted volume configuration files not found in project directory";
+            exit 1;
+          fi
